version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"